entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'

providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: suphotsudsee@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
